image: gitpod/workspace-full-vnc

tasks:
  - name: Install
    init: |
      pip install -r requirements.txt
      npx --yes playwright install-deps
      gp sync-done pip
  - name: Install Playwright Deps
    init: gp sync-await pip
    command: rfbrowser init
  - name: Install Allure
    init: gp sync-await pip
    command: |
      wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
      tar -xzf allure-2.25.0.tgz
      rm allure-2.25.0.tgz
ports:
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode
    - ms-azuretools.vscode-docker
    - ckolkman.vscode-postgres